"""empty message

Revision ID: fed1ebe6bd03
Revises: 833724243ce0
Create Date: 2022-08-22 11:40:30.209885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed1ebe6bd03'
down_revision = '833724243ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bags', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bags', 'title')
    # ### end Alembic commands ###
